---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ciborg9.
--- DateTime: 02/07/2020 18:03
---
Config = {}
Config.giveMoney = true
Config.amountGiven = 1500
Config.addMoneyOfflinePlayer = true